services:
  - type: web
    name: delivery-proof-server
    runtime: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "5000"
      - key: JWT_SECRET
        generateValue: true
      - key: DB_HOSTNAME
        value: mysql-265634-shoppingwithshopx-0ff0.j.aivencloud.com
      - key: DB_PORT
        value: "13111"
      - key: DB_USERNAME
        value: avnadmin
      - key: DB_PASSWORD
        sync: false
      - key: DB_SCHEMA
        value: defaultdb
      - key: DB_SSL
        value: "true"
      - key: CLOUDINARY_CLOUD_NAME
        value: dtvzlhrzw
      - key: CLOUDINARY_API_KEY
        value: "321829124669296"
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: CLOUDINARY_KEY_NAME
        value: DeliveryProof
